In [1]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn import ensemble

/home/pulkit/.local/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/pulkit/.local/lib/python2.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
data = pd.read_csv("Dell_data.csv")
data.tail(5)

asin  C1  C2  C3  P1  P2  P3 Review Sentiment  Service Rating  \
545  B006NTK3MM   5   5   0   3   5   2              2.4               1   
546  B006NWJBZE   5   4   1   4   2   4             2.43               0   
547  B006NXX5YG   6   3   1   5   1   4              1.8               3   
548  B006OFWBE8   6   0   4   7   0   3             2.27               4   
549  B006OSNP5O   8   2   0   6   4   0              0.9               4   

    Customer Sentiment  
545                NaN  
546                NaN  
547                NaN  
548                NaN  
549                NaN

In [3]:
train = data[data.columns[1:9]][0:299]
target = data['Customer Sentiment'][0:299]

In [4]:
train.tail(5)

C1  C2  C3  P1  P2  P3 Review Sentiment  Service Rating
294   7   0   3   8   1   1             2.82               3
295   7   2   1   7   0   3             2.36               2
296   4   2   4   6   2   2             1.63               4
297   7   2   1   7   0   3              2.2               5
298   5   5   0   5   3   2             1.18               5

In [5]:
target.tail(5)

294    3.6
295    3.8
296      4
297    4.3
298    4.2
Name: Customer Sentiment, dtype: object

In [6]:
train.shape

(299, 8)

In [7]:
target.shape

(299,)

In [8]:
x_train , x_test , y_train , y_test = train_test_split(train , target , test_size = 0.33,random_state =2)

In [9]:
x_train.shape

(200, 8)

In [10]:
x_test.shape

(99, 8)

In [11]:
y_test.shape

(99,)

In [18]:
clf = ensemble.GradientBoostingRegressor(n_estimators = 400, max_depth = 3, min_samples_split = 2,
          learning_rate = 0.1, loss = 'ls')


In [19]:
clf.fit(x_train, y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=400, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

In [20]:
clf.score(x_test,y_test)

0.5657714069757358

In [21]:
from sklearn import linear_model


In [ ]:
clf2 = linear_model.Lasso(alpha=0.1)

In [26]:
clf3 = linear_model.LinearRegression()

In [34]:
clf4 = linear_model.LogisticRegression()

In [41]:
clf5 = linear_model.Ridge()

In [43]:
clf5.fit(x_train, y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [44]:
clf4.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [45]:
clf3.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [37]:
clf2.fit(x_train, y_train)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [38]:
clf2.score(x_test,y_test)

0.5082244212534229

In [39]:
clf3.score(x_test,y_test)

0.6662791086723769

In [40]:
clf4.score(x_test,y_test)

0.08080808080808081

In [46]:
clf5.score(x_test,y_test)

0.6642280089653422

In [29]:
clf.predict([[1,2,7,9,3,4,1.93,3]])

array([4.10159546])

In [30]:
clf.predict([[1,2,7,9,3,0,1.93,3]])

array([3.28513355])

In [31]:
clf.predict([[1,2,7,9,3,6,1.93,3]])


array([4.19868708])

In [32]:
clf.predict([[1,2,7,9,3,6,2.93,3]])

array([4.36239308])

In [33]:
clf.predict([[1,2,7,9,3,8,1.93,3]])

array([4.19868708])

In [34]:
clf.predict([[1,2,7,9,3,8,1.93,4]])

array([4.50642638])

In [37]:
clf.predict([[1,2,7,9,3,8,3.93,2]])

array([4.30308813])